services:
  - type: web
    name: magic-genie-explainer
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false  # This will be set manually in the Render dashboard
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: GEMINI_TEMPERATURE
        value: "0.6"
      - key: GEMINI_MAX_OUTPUT_TOKENS
        value: "250" 